# Generated by Django 3.0.3 on 2020-12-01 14:42

from django.db import migrations, models
import django.utils.timezone
import metatask.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default='groupName', max_length=32)),
                ('userList', metatask.models.ListField(default=['-1'], token=',')),
                ('taskList', metatask.models.ListField(default=['-1'], token=',')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(default='taskName', max_length=32)),
                ('userList', metatask.models.ListField(default=['-1'], token=',')),
                ('ddlTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='userName', max_length=32)),
                ('password', models.CharField(default='000000', max_length=32)),
                ('profession', models.CharField(default='undefined', max_length=32)),
                ('email', models.CharField(default='undefined', max_length=32)),
                ('phoneNumber', models.CharField(default='undefined', max_length=32)),
                ('area', models.CharField(default='undefined', max_length=32)),
                ('personHomepage', models.CharField(default='undefined', max_length=200)),
                ('note', models.TextField(default='undefined')),
                ('headImg', models.ImageField(default='img/default.jpg', upload_to='img/')),
                ('isOnline', models.IntegerField(default=0)),
                ('groupList', metatask.models.ListField(default=['-1'], token=',')),
                ('taskList', metatask.models.ListField(default=['-1'], token=',')),
            ],
        ),
    ]
